swagger: '2.0'
info:
  title: API Title
  version: '1.0'
host: "localhost:3000"
schemes:
  - http
  - https 
basePath: /v1
paths:
  /test:
    get:
      responses:
        '200':
          description: OK
  /users/login:
    post:
      responses:
        '200':
          description: OK
  /users/signup:
    post:
      summary: Create a new user
      description: Create a new user with provided name, email and password
      responses:
        '200':
          description: OK

  /products:
    get:
      responses:
        '200':
          description: OK